/* The data sources an explanation names under "Where it comes from", each
 * with how fresh it is on this page. A feed pulled on every refresh reads
 * "to 24 Sep", the day the page's data runs to (snap.asOf, ", so far" on a
 * part day), and carries a green dot; where the release's own last order or
 * last day of spend is earlier, that is named beside it ("last order 27
 * Aug"), a fact about the release rather than about the feed. The Emplifi
 * export of posts, a file regenerated by hand, reads to its own last day. An
 * input somebody set (the Target setting tab, Airtable, the basket) reads as
 * set, with a grey dot. Where the last refresh reported the feed behind it
 * failing (the header's Freshness line reads the same status), the dot turns
 * amber and says so. Plain JavaScript, so the tests can read it. */
import { fmtDay } from "../format.mjs";

const day = (iso) => (iso ? fmtDay(new Date(String(iso).slice(0, 10) + "T00:00:00Z")) : null);
const FAILED = /failed|misconfigured|stale/i;

/* The last day of the Meta spend on the page: the last row of paid.daily
 * with spend on it (the as-of day so far rides last, marked partial). */
function lastSpend(s) {
  const rows = (s.paid && s.paid.daily) || [];
  for (let i = rows.length - 1; i >= 0; i--) {
    if ((rows[i].spend ?? 0) > 0) return rows[i];
  }
  return null;
}

const partialDay = (s) => typeof s.asOfFraction === "number" && s.asOfFraction < 1;

/* A feed's reach: the day the page's data runs to, the part day said. */
const reach = (s) => (s.asOf ? `to ${day(s.asOf)}${partialDay(s) ? ", so far" : ""}` : null);
/* ...and the release's own last activity in it, named, where that is earlier. */
const withLast = (s, word, iso) => {
  const r = reach(s);
  if (!r) return iso ? `${word} ${day(iso)}` : null;
  return iso && String(iso).slice(0, 10) < String(s.asOf).slice(0, 10) ? `${r} · ${word} ${day(iso)}` : r;
};

export const SOURCES = {
  orders: {
    name: "Shopify orders", via: "BigQuery · Order_Line_Concept", feed: "bigquery",
    // the orders table is pulled on every refresh; ordersAsOf is this
    // release's last order or draft day, not how far the table reaches
    fresh: (s) => withLast(s, "last order", (s.sellthrough && s.sellthrough.ordersAsOf) || (s.framing && s.framing.asOf) || null),
  },
  funnel: {
    name: "Funnel report", via: "BigQuery · LE Funnel Report", feed: "bigquery",
    fresh: (s) => (partialDay(s) && s.completeThrough
      ? `complete to ${day(s.completeThrough)}, ${day(s.asOf)} so far`
      : s.asOf ? `to ${day(s.asOf)}` : null),
  },
  entries: {
    name: "Draw entries", via: "BigQuery · LE Funnel Report events", feed: "bigquery",
    fresh: (s) => (s.asOf ? `to ${day(s.asOf)}` : null),
  },
  meta: {
    name: "Meta ads", via: "BigQuery · Meta ads insights", feed: "bigquery",
    // the spend feed is pulled on every refresh; the last day with spend on
    // it is this campaign's, named beside the feed's reach when earlier
    fresh: (s) => {
      const r = lastSpend(s);
      return withLast(s, "last spend", r ? r.date : null);
    },
  },
  hubspot: {
    name: "HubSpot emails", via: "HubSpot marketing sends", feed: "emails",
    fresh: (s) => (s.email && s.email.feedThrough ? `sends to ${day(s.email.feedThrough)}` : null),
  },
  social: {
    name: "Social posts",
    via: (s) => (s.social && s.social.postsSource === "notion" ? "Notion content log" : "Emplifi export"),
    feed: (s) => (s.social && s.social.postsSource === "notion" ? "notion" : null),
    // the Emplifi export reaches only as far as its last row (social.postsThrough)
    fresh: (s) => (s.social && s.social.postsSource !== "notion" && s.social.postsThrough
      ? `to ${day(s.social.postsThrough)}`
      : s.asOf ? `to ${day(s.asOf)}` : null),
  },
  airtable: {
    name: "Airtable", via: "Pipeline table", feed: "airtable",
    set: "set in Airtable",
  },
  settings: {
    name: "Target setting", via: "This dashboard's tab",
    set: "set here",
  },
  basket: {
    name: "Comparable launches",
    via: (s) => {
      const b = s.benchmark && s.benchmark.basket;
      return b ? `The basket "${b.name}", ${b.n} launches` : "The benchmark basket";
    },
    set: "chosen here",
  },
  curves: {
    name: "Past launches", via: "The basket's across-time curves",
    set: "fitted",
  },
  rules: {
    name: "Spend rules", via: "The TL template's ROI / spend rules",
    set: "fixed",
  },
  dates: {
    name: "Campaign dates",
    via: (s) => {
      const how = s.inputSources && s.inputSources.announce_date;
      return how === "notion" ? "The Notion campaign log"
        : how === "typed" ? "Typed on the Target setting tab"
        : how === "airtable" ? "Airtable's planned dates"
        : "The funnel export's campaign clock";
    },
    set: "set",
  },
};

/* One source as the panel shows it: its name, where it is read from, what it
 * gave this figure, and either its freshness or how it was set. */
export function sourceRow({ key, gave }, snap, st) {
  const src = SOURCES[key];
  if (!src) return { name: key, via: "", gave, fresh: null, set: null, warn: null };
  const s = snap || {};
  const via = typeof src.via === "function" ? src.via(s) : src.via;
  const feed = typeof src.feed === "function" ? src.feed(s) : src.feed;
  const status = feed && st ? st[feed] : null;
  const warn = status && FAILED.test(String(status)) ? "last refresh failed" : null;
  return {
    name: src.name, via, gave,
    fresh: src.fresh ? src.fresh(s) : null,
    set: src.set || null,
    warn,
  };
}
